### ISSUE TITLE
How can I get this article?

### ISSUE THREAD

**Issue by yunyunandruirui** [xiangwang1223/knowledge_graph_attention_network#1]
It seems that the url of the paper is invalid. I can't find your paper on the Internet. How can I get this article?

**Comment by rillhu** [comment]
same here. The download url is invalid. Could you please update the article download link? Thanks!

**Comment by xiangwang1223** [comment]
Hi, sorry for the invalid url. I am still working on the camera-ready version. The preprint will be released in the later three weeks. Thanks for your consideration.

**Comment by xiangwang1223** [comment]
Hi @yunyunandruirui @rillhu, now you can get the preprint of our paper via the valid url. Thanks for all your interest.
