### ISSUE TITLE
Could you provide the actual semantics corresponding to each item&entity in KG?

### ISSUE THREAD

**Issue by wonniu** [xiangwang1223/knowledge_graph_attention_network#14]
Hi Dr. Wang,

Thanks for you wonderful work. To get more intuitive understanding of your proposed method, I would like to conduct some case study on your provided datasets. However, the actual semantics of the items and entities are not available. Could you provide the actual semantics corresponding to each item&entity in KG?

Best

**Comment by xiangwang1223** [comment]
Thanks for your interest. We provide the original id mapping to the original files.
1. For yelp2018, you can easily get the semantics of items and relations in the original yelp2018 dataset.
2. For the others, you need to download the freebase and parse it to get the semantics.
