### ISSUE TITLE
I don't quite understand how you did CaseStudy.

### ISSUE THREAD

**Issue by CXX1113** [xiangwang1223/knowledge_graph_attention_network#16]
I don't quite understand how you did CaseStudy. When you calculate the attention score, it is calculated for each triple above the entire CKG. There is no information about the same (user, item) pair as constraint information. So, when KGAT training is complete, your attention score is based on the entire training set. The only way I can think of at the moment is that when you need CaseStudy, you need to retrain KGAT, and CF batch has only one (user, item) pair. Maybe you can provide code about CaseStudy. Thank you!

**Comment by saahilgupta93** [comment]
Hi, it will be super useful if you can guide us through the steps for implementing the case study- need info to fetch the **retrieved paths** to form a graph from user to item as shown in the research paper.
Thanks a lot in advance! :)

**Comment by annoyedprogrammer** [comment]
Hi,
Any suggestions around the process of reproducing the Case Study?
Thank you in advance! Big Fan of your work..

**Comment by xiangwang1223** [comment]
Sorry for the late reply after the busy weeks. Thanks for your interest. I conduct the case study via the following steps:
1. When the training is done, the model parameters (including user, item, KG entity, and KG relation embeddings) are fixed.

2. Given a user-item pair of interest, you can run the random walker to get the paths connecting the user and the item; moreover, random walks or paths help us to filter the irrelevant entities out.

3. Based on the model parameters, you can get the attention scores for each triplet based on Equations (4) and (5) in the paper.

4. Note that there is no need to retrain the model. You can obtain the attention scores for arbitrary numbers of user-item pairs.

Hope that it can be helpful. Thanks!

**Comment by annoyedprogrammer** [comment]
Thankyou so much for your guidance :-)

**Comment by CXX1113** [comment]
Thank you. I see.
