### ISSUE TITLE
Code running issues

### ISSUE THREAD

**Issue by viviqi** [xiangwang1223/knowledge_graph_attention_network#21]
Thank you for sharing the code. I use the default parameters to run your data and code without any problems, but after I processed my data like yours, it will automatically exit after 2 epoches of running without error arising. If possible, could you please analyze what might be the reason? Thank you.
![Running Exit Photo](https://user-images.githubusercontent.com/49056139/70792999-57699c00-1dd5-11ea-8846-3ce809f44de7.png)

**Comment by viviqi** [comment]
The problem has been solved, I rerun code with GPU and it takes around 260S per epoch. Thank you anyway.

**Comment by wiany11** [comment]
@viviqi How did you run the code with GPU? Which option should I use?
