### ISSUE TITLE
I thing there may be some problem in the code implementation of the ndcg

### ISSUE THREAD

**Issue by manakanemu** [xiangwang1223/knowledge_graph_attention_network#27]
I don't know if my understanding of ndcg is correct, but i think
`return r[0] + np.sum(r[1:] / np.log2(np.arange(2, r.size + 1)))`,in `metrics.py` , line 53  
should be   
`return r[0] + np.sum(r[1:] / np.log2(np.arange(3, r.size + 2)))`

**Comment by bruunand** [comment]
I think you are right @manakanemu, why did you close the issue?
