### ISSUE TITLE
How to run the code with GPU?

### ISSUE THREAD

**Issue by wiany11** [xiangwang1223/knowledge_graph_attention_network#33]
How can I run the code using GPU?

It utilizes GPU on my laptop but does not on a cloud.

How can I force it to use GPU?

Thanks,

**Comment by wiany11** [comment]
`with tf.device('/gpu:0')` worked...

**Comment by empty-id** [comment]
Hi @wiany11 , where to add ```with tf.device('/gpu:0')```?

**Comment by wiany11** [comment]
@null-id  I put it between https://github.com/xiangwang1223/knowledge_graph_attention_network/blob/c03737be46ac26a0b5431efe149828e982ffbbfb/Model/Main.py#L113-L114. Sorray for the late reply.
