### ISSUE TITLE
Movielens 20M

### ISSUE THREAD

**Issue by nickspell** [xiangwang1223/knowledge_graph_attention_network#9]
hello, I would like to ask you if there is a reason why you haven't released training code (and results on paper) for the Movielens dataset and if you plan to do it in near future. Thanks.

**Comment by xiangwang1223** [comment]
Hi, we actually performed KGAT on MovieLens-1M, and are working on MovieLens-20M currently. We will update the performance in our future work. Thanks.

**Comment by sachinsharma9780** [comment]
Hi @xiangwang1223 ,

Is it possible to release the data/KG which you have built out of MovieLens-1M?

Thanks!!
